name: Main build

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

jobs:
  main_array:
    name: main array
    uses: ./.github/workflows/reusable-wf.yaml
    with:
      my_variable: '["str1", "str2"]'

  main string:
    name: main string
    uses: ./.github/workflows/reusable-wf.yaml
    with:
      my_variable: str1
      


