name: Convert to Array in Multiple Steps

on:
  workflow_dispatch:
    inputs:
        my_variable:
          description: 'variable name'
          required: true


jobs:
  convert_to_array:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Step 1 - Use convert_to_array function
        run: |
          convert_to_array() {
            if [[ $1 =~ "\[*\]" ]]; then
              echo $1
            else
              echo "[\"$1\"]"
            fi
          }
          echo "value to convert: ${{ inputs.my_variable }}"
          converted_variable=$(convert_to_array ${{ "inputs.my_variable" }})
          echo "Converted variable in Step 1: $converted_variable"
          for item in $(echo "${converted_variable}" | jq -r '.[]'); do
            echo "Item: ${item}"
          done

      - name: Step 2 - Use convert_to_array function
        run: |
          convert_to_array() {
            if [[ $1 =~ "\[*\]" ]]; then
              echo "$1"
            else
              echo "[\"$1\"]"
            fi
          }

          converted_variable=$(convert_to_array ${{ "inputs.my_variable" }})
          echo "Converted variable in Step 2: $converted_variable"
          for item in $(echo "${converted_variable}" | jq -r '.[]'); do
            echo "Item: ${item}"
          done