name: Main build

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

jobs:
  with_array:
    name: with array
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reusable-wf.yaml
    with:
      my_variable: '["str1", "str2"]'
      
  with_string:
    name: with string
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reusable-wf.yaml
    with:
      my_variable: str1
      


