name: Main build

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

jobs:
  main:
    name: main job
    runs-on: ubuntu-latest
    steps:
      - name: try array
        uses: ./.github/workflows/reusable-wf.yaml
        with:
          my_variable: '["str1", "str2"]'
      - name: try string
        uses: ./.github/workflows/reusable-wf.yaml
        with:
          my_variable: str1
      


