name: Convert to Array in Multiple Steps

on:
  workflow_dispatch:
    inputs:
        my_variable:
          description: 'variable name'
          required: true


jobs:
  convert_to_array:
    runs-on: ubuntu-latest
    steps:
      - name: Convert input to JSON array
        id: json_array
        run: |
          input_var="${{ inputs.my_variable }}"
          if [[ $(echo "$input_var" | jq -e . >/dev/null 2>&1; echo $?) -eq 0 ]]; then
            echo "::set-output name=items::$input_var"
          else
            echo "::set-output name=items::$( echo "[$input_var]" | jq . )"
          fi

      - name: Use convert_to_array function
        run: |
          echo "Converted variable in Step 1: $converted_variable"
          for item in $(echo "${{ steps.json_array.outputs.items }}" | jq -r '.[]'); do
            echo "Item: ${item}"
          done
